%==========================================================================
% gen_weight_window.m
%
% Function: Generate the weighting window function for the H3 observation
%           plane and save it to Weight.txt.
%
% Principle:
%   The H3 observation plane has 153 sample points in total. The target
%   field pattern is distributed only in the central region (points 47~106).
%   The weighting window is set to 1 in this region and 0 at both ends,
%   so that the fitness evaluation focuses only on the valid signal region
%   and suppresses the interference of edge zero-field values on the
%   correlation coefficient computation.
%
% Window function structure (153 points total):
%   Points   1 ~  46: 0 (left invalid region)
%   Points  47 ~ 106: 1 (central valid region, 61 points)
%   Points 107 ~ 153: 0 (right invalid region)
%
% Output file:
%   Weight.txt  — weighting window function (1x153, integer vector of 0/1)
%
% Dependency:
%   Weight.txt generated by this script is read by eval_field_correlation.m
%   to compute the weighted correlation coefficient between the H3 field
%   and the target field pattern.
%
%==========================================================================

clc;
clear;

%% ========================================================================
%  Part 1: Parameter definition
%% ========================================================================

n3x          = 153;   % total sample points on H3 observation plane (consistent with calc_H_field.m)
window_start = 47;    % start index of the valid region (inclusive)
window_end   = 106;   % end index of the valid region (inclusive)

%% ========================================================================
%  Part 2: Build the weighting window function
%% ========================================================================

% Initialize to all zeros
h_window = zeros(1, n3x);

% Set the central valid region to 1
h_window(window_start : window_end) = 1;

n_active = window_end - window_start + 1;   % number of valid points = 61
fprintf('Window function built: total points %d, valid points %d (indices %d~%d)\n', ...
        n3x, n_active, window_start, window_end);

%% ========================================================================
%  Part 3: Save to file
%% ========================================================================

dlmwrite('Weight.txt', h_window, 'delimiter', ' ', 'precision', 4);
fprintf('Saved to: Weight.txt\n');

%% ========================================================================
%  Part 4: Preview plot
%% ========================================================================

figure(1);
stem(h_window, 'b', 'LineWidth', 1.2, 'MarkerSize', 3);
xlabel('H3 Plane Sample Index');
ylabel('Weight Value (0 or 1)');
title(sprintf('Weighting Window Function (valid region: points %d~%d)', window_start, window_end));
ylim([-0.1, 1.3]);
grid on;
